<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>YFilter</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
<header>
    <h1>Youtube Search</h1>
    <form action="/">
        <fieldset>
            <legend>Start Searching</legend>
                <label for="search">Search:</label>
                <input type="text" name="search" id="search" value="<?php if($search)echo $search ?>">
                <input type="submit" value="find">
        </fieldset>
        <fieldset>
            <legend>Time</legend>
                <input type="radio" name="time" id="short" value="short"
                    <?php if($time == "short")echo "checked" ?>><label for="short">0 Untill 4:00</label>
                <input type="radio" name="time" id="medium" value="medium"
                    <?php if($time == "medium")echo "checked" ?>><label for="medium">4:00 Untill 20:00</label>
                <input type="radio" name="time" id="long" value="long"
                    <?php if($time == "long")echo "checked" ?>><label for="long">20:00 And Up</label>
                <input type="radio" name="time" id="any" value="any"
                    <?php if($time == "any" || !isset($time))echo "checked" ?>><label for="any">Any</label>
        </fieldset>
        <!-- <fieldset>
            <legend>Channel Type</legend>
                <input type="radio" name="channelType" id="show" value="show"
                    <?php if($channelType == "show")echo "checked" ?>><label for="show">Only retrieve shows</label>
                <input type="radio" name="channelType" id="any" value="any"
                    <?php if($channelType == "any" || !isset($channelType))echo "checked" ?>><label for="any">Return all channels</label>
        </fieldset> -->
        <fieldset>
            <legend>Type</legend>
                <input type="radio" name="type" id="channel" value="channel"
                    <?php if($type == "channel")echo "checked" ?>><label for="channel">Channel</label>
                <input type="radio" name="type" id="playlist" value="playlist"
                    <?php if($type == "playlist")echo "checked" ?>><label for="playlist">Playlist</label>
                <input type="radio" name="type" id="video" value="video"
                    <?php if($type == "video"|| !isset($type))echo "checked" ?>><label for="video">Video</label>
        </fieldset>
    </form>
</header>
<?php if ($html) ?>
<main>
    <?php echo $html ?>
</main>
<?php ?>
<footer>
    <p>For support:<a href="https://twitter.com/darkbelg">@Darkbelg</a></p>
</footer>
</body>
</html>